#include<iostream>
#include<chrono>
#include<thread>
#include<filesystem>
#include<linuxsampler/Sampler.h>
#include<linuxsampler/drivers/audio/AudioOutputDeviceFactory.h>

namespace fs = std::__fs::filesystem;

int main() {
    auto sampler = new LinuxSampler::Sampler();
    auto factory = new LinuxSampler::AudioOutputDeviceFactory();

    auto params = std::map<std::string, std::string>();
    params["BUFFERSIZE"] = "2048";
    params["BUFFERS"] = "4";
    auto device = factory->Create("COREAUDIO", params);
auto flute = sampler->AddSamplerChannel();
flute->SetAudioOutputDevice(device);
flute->SetEngineType("SFZ");
flute->GetEngineChannel()->PrepareLoadInstrument(
(fs::current_path() / ".." / ".." / "resources" / "sfz" / "Jeux14" / "000/025_Trompette_8.sfz").string().c_str(),
  0);
flute->GetEngineChannel()->LoadInstrument();

auto pedal = sampler->AddSamplerChannel();
pedal->SetAudioOutputDevice(device);
pedal->SetEngineType("SFZ");
pedal->GetEngineChannel()->PrepareLoadInstrument(
(fs::current_path() / ".." / ".." / "resources" / "sfz" / "Jeux14" / "000/015_Bourdon_16.sfz").string().c_str(),
  0);
pedal->GetEngineChannel()->LoadInstrument();

auto piano = sampler->AddSamplerChannel();
piano->SetAudioOutputDevice(device);
piano->SetEngineType("SFZ");
piano->GetEngineChannel()->PrepareLoadInstrument(
(fs::current_path() / ".." / ".." / "resources" / "sfz" / "Jeux14" / "000/000_Montre_8.sfz").string().c_str(),
  0);
piano->GetEngineChannel()->LoadInstrument();

 std::this_thread::sleep_for(std::chrono::milliseconds(1000));
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(50, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
pedal->GetEngineChannel()->SendNoteOff(50, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(48, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(58, 80, 0);
pedal->GetEngineChannel()->SendNoteOff(48, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(46, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(58, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(58, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(58, 80, 0);
pedal->GetEngineChannel()->SendNoteOff(46, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(43, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(58, 80, 0);
piano->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(63, 80, 0);
piano->GetEngineChannel()->SendNoteOn(67, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(67, 80, 0);
piano->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(58, 80, 0);
piano->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(63, 80, 0);
piano->GetEngineChannel()->SendNoteOn(67, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(67, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
pedal->GetEngineChannel()->SendNoteOff(43, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(45, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(61, 80, 0);
piano->GetEngineChannel()->SendNoteOn(67, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(67, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(64, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(64, 80, 0);
piano->GetEngineChannel()->SendNoteOn(55, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(55, 80, 0);
piano->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(61, 80, 0);
piano->GetEngineChannel()->SendNoteOn(64, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(64, 80, 0);
piano->GetEngineChannel()->SendNoteOn(53, 80, 0);
pedal->GetEngineChannel()->SendNoteOff(45, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(50, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(53, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
flute->GetEngineChannel()->SendNoteOn(69, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(62, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(62, 80, 0);
piano->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(76));
flute->GetEngineChannel()->SendNoteOff(69, 80, 0);
flute->GetEngineChannel()->SendNoteOn(69, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(227));
piano->GetEngineChannel()->SendNoteOff(65, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
pedal->GetEngineChannel()->SendNoteOff(50, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(49, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(0));
flute->GetEngineChannel()->SendNoteOff(69, 80, 0);
flute->GetEngineChannel()->SendNoteOn(69, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(64, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(64, 80, 0);
piano->GetEngineChannel()->SendNoteOn(67, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(67, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(64, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(64, 80, 0);
piano->GetEngineChannel()->SendNoteOn(67, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(67, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(64, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(64, 80, 0);
piano->GetEngineChannel()->SendNoteOn(67, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(67, 80, 0);
piano->GetEngineChannel()->SendNoteOn(57, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(0));
flute->GetEngineChannel()->SendNoteOff(69, 80, 0);
flute->GetEngineChannel()->SendNoteOn(69, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(57, 80, 0);
piano->GetEngineChannel()->SendNoteOn(64, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(303));
piano->GetEngineChannel()->SendNoteOff(64, 80, 0);
piano->GetEngineChannel()->SendNoteOn(67, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(76));
flute->GetEngineChannel()->SendNoteOff(69, 80, 0);
flute->GetEngineChannel()->SendNoteOn(69, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(227));
piano->GetEngineChannel()->SendNoteOff(67, 80, 0);
pedal->GetEngineChannel()->SendNoteOff(49, 80, 0);
flute->GetEngineChannel()->SendNoteOff(69, 80, 0);
 std::this_thread::sleep_for(std::chrono::milliseconds(1000));
}
